package com.example.hyprerone.model;


import com.example.hyprerone.dto.InvoiceDto;
import com.example.hyprerone.dto.ProductDto;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "invoice")
@Accessors(chain = true)
public class Invoice {


    @Id // this field's value will be generated by hibernate sequence
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;


    @Column(name = "invoice_number")
    private Integer invoiceNumber;

    @Column(name = "date")
    private Date date;

    @ManyToOne(fetch = FetchType.EAGER, targetEntity = Product.class)
    @JoinColumn(name = "product_Id", foreignKey = @ForeignKey(name = "fk_product"))
    private Product productId;

    @Column(name = "total_proice")
    private Integer totalPrice;

    @Column(name = "number_of_product")
    private Integer numberOfProduct;

    // setting invoice properties
    public Invoice fromDto(InvoiceDto dto) {
        Invoice invoice = new Invoice();
//        invoice.setId(dto.getId());
        invoice.setInvoiceNumber(dto.getInvoiceNumber());
        invoice.setDate(dto.getDate());
        invoice.setProductId(invoice.getProductId());
        invoice.setTotalPrice(dto.getTotalPrice());
        invoice.setNumberOfProduct(dto.getNumberOfProduct());
        return invoice;
    }

    public InvoiceDto fromInvoiceModel(Invoice invoice) {
        InvoiceDto dto = new InvoiceDto();
//        dto.setId(invoice.getId());
        dto.setInvoiceNumber(invoice.getInvoiceNumber());
        dto.setDate(invoice.getDate());
        dto.setProductId(dto.getProductId());
        dto.setTotalPrice(invoice.getTotalPrice());
        dto.setNumberOfProduct(dto.getNumberOfProduct());
        return dto;
    }
}
